services:
  # Laravel Application Service
  app:
    build:
      context: app/.
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql
    working_dir: /var/www/html
    environment:
      - "DB_HOST=mysql"
      - "DB_PORT=3309"
      - "DB_DATABASE=commandvault"
      - "DB_USERNAME=commander"
      - "DB_PASSWORD=fHKHeWEhN9s_Me-ny4/,P"
    ports:
      - "8000:80"

  # MySQL Database Service
  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: commander
      MYSQL_DATABASE: fHKHeWEhN9s_Me-ny4/,P
    ports:
      - "3309:3306"
    networks:
      - app-network

  # Nginx web server
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./app:/var/www/html
    networks:
      - app-network
    ports:
      - "8880:80"
    depends_on:
      - app

networks:
  app-network:
    driver: bridge